version: "3.8"

services:
 backend:
  build:
   context: ./backend
   dockerfile: Dockerfile
  ports:
   - "8080:8080"
  depends_on:
   db:
    condition: service_healthy
  env_file:
   - .env.local
  networks:
   - kotobalize-net

 frontend:
  build:
   context: ./frontend
   dockerfile: Dockerfile.dev # Use development Dockerfile
  ports:
   - "3000:3000"
  volumes:
   # Mount host source code to container and enable hot reload
   # :delegated improves performance on macOS
   - ./frontend:/app:delegated
   # Prevent container's node_modules from being overwritten by host's one
   - /app/node_modules
  # Dockerfile.dev sets CMD so command is not needed
  # command: npm run dev  # <- This line is deleted
  depends_on:
   - backend
  env_file:
   - .env.local
  environment:
   - NODE_ENV=development # Indicates this is development environment
  networks:
   - kotobalize-net

 db:
  image: mysql:8.0
  container_name: kotobalize-db
  restart: always
  env_file:
   - .env.local
  healthcheck:
   test:
    [
     "CMD",
     "mysqladmin",
     "ping",
     "-h",
     "localhost",
     "-u",
     "root",
     "-prootpassword",
    ]
   interval: 10s
   timeout: 5s
   retries: 5
   start_period: 10s
  ports:
   - "3306:3306"
  volumes:
   - mysql-data:/var/lib/mysql
  networks:
   - kotobalize-net

networks:
 kotobalize-net:
  driver: bridge

volumes:
 mysql-data:
  driver: local
