version: "3.8"

services:
 backend:
  build:
   context: ./backend/generated-server
  ports:
   - "8080:8080"
  depends_on:
   db:
    condition: service_healthy
  environment:
   # Connection information for the backend to communicate with the DB container
   - DB_USER=kotobalize_user
   - DB_PASSWORD=kotobalize_password
   - DB_HOST=db
   - DB_PORT=3306
   - DB_NAME=kotobalize_db
   - JWT_SECRET=a_very_secret_key_that_should_be_changed
   - OPENAI_API_KEY=your_openai_api_key_here #TODO: Change this to your OpenAI API key
  networks:
   - kotobalize-net

 frontend:
  build:
   context: ./frontend
  ports:
   - "3000:3000"
  volumes:
   # ホストのソースコードをコンテナにマウントして、ホットリロードを有効にします
   # :delegated はmacOSでのパフォーマンスを向上させます
   - ./frontend:/app:delegated
   # コンテナ内のnode_modulesがホストのもので上書きされるのを防ぎます
   - /app/node_modules
  # DockerfileのCMDを上書きし、開発サーバーを起動します
  command: npm run dev
  depends_on:
   - backend
  environment:
   # URL for the frontend to communicate with the backend API
   - NEXT_PUBLIC_API_URL=http://backend:8080/api/v1
  networks:
   - kotobalize-net

 db:
  image: mysql:8.0
  container_name: kotobalize-db
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: rootpassword
   MYSQL_DATABASE: kotobalize_db
   MYSQL_USER: kotobalize_user
   MYSQL_PASSWORD: kotobalize_password
  healthcheck:
   test:
    [
     "CMD",
     "mysqladmin",
     "ping",
     "-h",
     "localhost",
     "-u",
     "root",
     "-prootpassword",
    ]
   interval: 10s
   timeout: 5s
   retries: 5
   start_period: 10s
  ports:
   # MySQL port mapping
   - "3306:3306"
  volumes:
   # MySQL data persistence
   - mysql-data:/var/lib/mysql
  networks:
   - kotobalize-net

networks:
 kotobalize-net:
  driver: bridge

volumes:
 mysql-data:
  driver: local
