run:
 timeout: 5m
 go: "1.23"

linters:
 enable:
  - govet
  - errcheck
  - staticcheck
  - unused
  - ineffassign
  - gocyclo
  - misspell
  - nolintlint

issues:
 max-issues-per-linter: 0
 max-same-issues: 0
 exclude-dirs:
  - go # Skip the generated go directory
  - vendor
