run:
 timeout: 5m
 go: "1.23"

linters:
 enable:
  - govet
  - errcheck
  - staticcheck
  - unused
  - ineffassign
  - gocyclo
  - misspell
  - nolintlint
 exclusions:
  paths:
   - go
   - vendor

formatters:
 enable:
  - goimports
  - golines
  - swaggo
 exclusions:
  paths:
   - go
   - vendor

issues:
 max-issues-per-linter: 0
 max-same-issues: 0
