run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
  disable:
    - structcheck  # deprecated
    - deadcode     # deprecated
    - varcheck     # deprecated
    - typecheck     # temporarily disabled due to jwt import issues

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - go  # Skip the generated go directory
    - vendor