version: 1.0.0

run:
 timeout: 5m

linters:
 enable:
  - goimports
  - govet
  - errcheck
  - staticcheck
  - unused
  - ineffassign
  - typecheck
  - gocyclo # Default threshold is 30
  - misspell
  - nolintlint
