/*
 * Kotobalize API
 *
 * API for the Kotobalize technical interview preparation app.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type UsersAPI struct {
}

// Delete /api/v1/users/me/avatar
// Delete user's avatar 
func (api *UsersAPI) DeleteUserAvatar(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /api/v1/users/me/avatar/upload-url
// Get a presigned URL for avatar upload 
func (api *UsersAPI) GetAvatarUploadURL(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /api/v1/users/me/avatar
// Update user's avatar URL 
func (api *UsersAPI) UpdateUserAvatar(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /api/v1/users/me/password
// Update current user's password 
func (api *UsersAPI) UpdateUserPassword(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Put /api/v1/users/me
// Update current user's profile 
func (api *UsersAPI) UpdateUserProfile(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

