/*
 * Kotobalize API
 *
 * API for the Kotobalize technical interview preparation app.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type LoginRequest struct {
	Email string `json:"email"`

	Password string `json:"password"`

	// If true, the token will have a longer expiration time.
	RememberMe bool `json:"rememberMe,omitempty"`
}
