/*
 * Kotobalize API
 *
 * API for the Kotobalize technical interview preparation app.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Theme struct {

	Id int64 `json:"id"`

	Title string `json:"title"`

	Description string `json:"description"`

	Category string `json:"category"`

	TimeLimitInSeconds int32 `json:"timeLimitInSeconds"`

	CreatedAt time.Time `json:"createdAt"`

	UpdatedAt time.Time `json:"updatedAt"`

	// ID of the user who created the theme. Null for official themes.
	CreatorId int64 `json:"creatorId,omitempty"`
}
