/*
 * Kotobalize API
 *
 * API for the Kotobalize technical interview preparation app.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Writing struct {
	Id int64 `json:"id"`

	UserId int64 `json:"userId"`

	ThemeId int64 `json:"themeId"`

	Content string `json:"content"`

	DurationSeconds int32 `json:"durationSeconds"`

	// The total score from 0 to 100.
	AiScore int32 `json:"aiScore,omitempty"`

	// Detailed feedback from AI based on 5 viewpoints. This will be stored as a JSON string.
	AiFeedback string `json:"aiFeedback,omitempty"`

	CreatedAt time.Time `json:"createdAt"`

	UpdatedAt time.Time `json:"updatedAt"`
}
