/*
 * Kotobalize API
 *
 * API for the Kotobalize technical interview preparation app.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AvatarUploadResponse struct {
	UploadUrl string `json:"uploadUrl"`

	Key string `json:"key"`
}
