name: Continuous Deployment

on:
 push:
  branches: [main]

env:
 GAR_LOCATION: asia-northeast1 # e.g. us-central1
 REPOSITORY: kotobalize # Artifact Registry repository name

jobs:
 deploy:
  name: Build and Deploy
  runs-on: ubuntu-latest
  permissions:
   contents: "read"
   id-token: "write"

  steps:
   - name: Checkout repository
     uses: actions/checkout@v4

   - name: Authenticate to GCP
     uses: google-github-actions/auth@v2
     with:
      project_id: ${{ secrets.GCP_PROJECT_ID }}
      credentials_json: ${{ secrets.GCP_SA_KEY }}

   # --- Backend Deployment ---
   - name: Build and Push Backend Docker image
     uses: docker/build-push-action@v5
     with:
      context: ./backend
      file: ./backend/Dockerfile
      push: true
      tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/kotobalize-backend:${{ github.sha }}

   - name: Deploy Backend to Cloud Run
     id: deploy_backend
     uses: google-github-actions/deploy-cloudrun@v2
     with:
      service: kotobalize-backend
      region: ${{ env.GAR_LOCATION }}
      image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/kotobalize-backend:${{ github.sha }}
      flags: >-
       --add-cloudsql-instances=${{ secrets.GCP_CLOUDSQL_INSTANCE_CONNECTION_NAME }}
       --set-secrets=DATABASE_URL=DATABASE_URL:latest,JWT_SECRET=JWT_SECRET:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID:latest,AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY:latest
       --set-env-vars=AWS_REGION=${{ secrets.AWS_REGION }},S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
       --allow-unauthenticated

   # --- Frontend Deployment ---
   - name: Build and Push Frontend Docker image
     uses: docker/build-push-action@v5
     with:
      context: ./frontend
      file: ./frontend/Dockerfile
      push: true
      tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/kotobalize-frontend:${{ github.sha }}
      build-args: |
       NEXT_PUBLIC_API_URL=${{ steps.deploy_backend.outputs.url }}

   - name: Deploy Frontend to Cloud Run
     uses: google-github-actions/deploy-cloudrun@v2
     with:
      service: kotobalize-frontend
      region: ${{ env.GAR_LOCATION }}
      image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/kotobalize-frontend:${{ github.sha }}
      flags: >-
       --allow-unauthenticated
